###########################################################################
###########################################################################
##
##  Docker Compose File: Portainer (Portainer.io)
##  Function: Alternate GUI Manager for Docker
##
##  Documentation: https://docs.portainer.io/start/install/server/docker
##
###########################################################################
###########################################################################

name: ${MEDIA_STACK_PROJECT_NAME:-media-stack}

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${FOLDER_FOR_CONFIG_DATA:?err}/portainer:/data
    ports:
      - "${WEBUI_PORT_PORTAINER:?err}:9000"
    network_mode: bridge
